In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("/content/emails.csv")

In [3]:
data.head(10)

Email No.  the  to  ect  and  ...  military  allowing  ff  dry  Prediction
0   Email 1    0   0    1    0  ...         0         0   0    0           0
1   Email 2    8  13   24    6  ...         0         0   1    0           0
2   Email 3    0   0    1    0  ...         0         0   0    0           0
3   Email 4    0   5   22    0  ...         0         0   0    0           0
4   Email 5    7   6   17    1  ...         0         0   1    0           0
5   Email 6    4   5    1    4  ...         0         0   0    0           1
6   Email 7    5   3    1    3  ...         0         0   0    0           0
7   Email 8    0   2    2    3  ...         0         0   1    0           1
8   Email 9    2   2    3    0  ...         0         0   0    0           0
9  Email 10    4   4   35    0  ...         0         0   0    0           0

[10 rows x 3002 columns]

In [4]:
data.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [5]:
data.describe()

the           to  ...          dry   Prediction
count  5172.000000  5172.000000  ...  5172.000000  5172.000000
mean      6.640565     6.188128  ...     0.006961     0.290023
std      11.745009     9.534576  ...     0.098086     0.453817
min       0.000000     0.000000  ...     0.000000     0.000000
25%       0.000000     1.000000  ...     0.000000     0.000000
50%       3.000000     3.000000  ...     0.000000     0.000000
75%       8.000000     7.000000  ...     0.000000     1.000000
max     210.000000   132.000000  ...     4.000000     1.000000

[8 rows x 3001 columns]

In [6]:
X = data.iloc[:,1:3001]

In [7]:
X

the  to  ect  and  for  ...  infrastructure  military  allowing  ff  dry
0       0   0    1    0    0  ...               0         0         0   0    0
1       8  13   24    6    6  ...               0         0         0   1    0
2       0   0    1    0    0  ...               0         0         0   0    0
3       0   5   22    0    5  ...               0         0         0   0    0
4       7   6   17    1    5  ...               0         0         0   1    0
...   ...  ..  ...  ...  ...  ...             ...       ...       ...  ..  ...
5167    2   2    2    3    0  ...               0         0         0   0    0
5168   35  27   11    2    6  ...               0         0         0   1    0
5169    0   0    1    1    0  ...               0         0         0   0    0
5170    2   7    1    0    2  ...               0         0         0   1    0
5171   22  24    5    1    6  ...               0         0         0   0    0

[5172 rows x 3000 columns]

In [8]:
Y = data.iloc[:,-1]

In [9]:
Y.values

array([0, 0, 0, ..., 1, 1, 0])

In [10]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.22)

In [11]:
NB = MultinomialNB(alpha=1.9)

In [12]:
x_train.shape

(4034, 3000)

In [13]:
x_test.shape

(1138, 3000)

In [14]:
y_train.shape

(4034,)

In [15]:
y_test.shape

(1138,)

In [16]:
NB.fit(x_train,y_train)

MultinomialNB(alpha=1.9, class_prior=None, fit_prior=True)

In [17]:
NB_ypredict1 = NB.predict(x_test)

In [18]:
NB_ypredict1

array([1, 1, 1, ..., 0, 1, 0])

In [19]:
print("Accuracy of Navie Bayes Classifier Model is {}".format(accuracy_score(y_test,NB_ypredict1)))

Accuracy of Navie Bayes Classifier Model is 0.9420035149384886


In [20]:
RF = RandomForestClassifier(n_estimators=100,criterion="gini")

In [21]:
RF.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [22]:
RF_ypredict2 = RF.predict(x_test)

In [23]:
RF_ypredict2

array([1, 1, 1, ..., 0, 1, 0])

In [24]:
print("Accuracy of Random Forest Classifier model is {}".format(accuracy_score(y_test,RF_ypredict2)))

Accuracy of Random Forest Classifier model is 0.976274165202109
